import { Row } from "../components/controls/customcomponent/grid/utils/types";


export const employeeRows: Row[] = [
  {
    Id: 1,
    EmployeeName: 'Aarav Mehta',
    Department: 'Engineering',
    Designation: 'Senior Developer',
    Email: 'aarav.mehta@example.com',
    Phone: '9876543210',
    City: 'Bangalore',
    JoinDate: '2023-05-10',
    Experience: 5,
    Manager: 'Neha Kapoor',
    Active: true,
    Salary: 1200000,
    Remarks: 'High performer, works on critical projects',
  },
  {
    Id: 2,
    EmployeeName: 'Diya Sharma',
    Department: 'Finance',
    Designation: 'Account Executive',
    Email: 'diya.sharma@example.com',
    Phone: '9823412345',
    City: 'Mumbai',
    JoinDate: '2022-11-01',
    Experience: 3,
    Manager: 'Rajesh Nair',
    Active: false,
    Salary: 900000,
    Remarks: 'On sabbatical leave',
  },
  {
    Id: 3,
    EmployeeName: 'Rohit Kumar',
    Department: 'HR',
    Designation: 'HR Manager',
    Email: 'rohit.kumar@example.com',
    Phone: '9998887776',
    City: 'Pune',
    JoinDate: '2024-02-15',
    Experience: 6,
    Manager: 'Meera Sen',
    Active: true,
    Salary: 750000,
    Remarks: 'Leads employee engagement initiatives',
  },
  {
    Id: 4,
    EmployeeName: 'Sara Iyer',
    Department: 'Engineering',
    Designation: 'Tech Lead',
    Email: 'sara.iyer@example.com',
    Phone: '9812345678',
    City: 'Chennai',
    JoinDate: '2021-08-22',
    Experience: 8,
    Manager: 'Neha Kapoor',
    Active: true,
    Salary: 1500000,
    Remarks: 'Excellent leadership and mentoring skills',
  },
  {
    Id: 5,
    EmployeeName: 'Kabir Jain',
    Department: 'Sales',
    Designation: 'Sales Executive',
    Email: 'kabir.jain@example.com',
    Phone: '9867895432',
    City: 'Delhi',
    JoinDate: '2020-01-05',
    Experience: 4,
    Manager: 'Vikas Sharma',
    Active: false,
    Salary: 650000,
    Remarks: 'Recently moved to part-time consultancy',
  },
  {
    Id: 6,
    EmployeeName: 'Priya Menon',
    Department: 'Marketing',
    Designation: 'Digital Marketing Lead',
    Email: 'priya.menon@example.com',
    Phone: '9845098765',
    City: 'Hyderabad',
    JoinDate: '2019-03-12',
    Experience: 7,
    Manager: 'Ravi Patel',
    Active: true,
    Salary: 1100000,
    Remarks: 'Handles social campaigns and analytics',
  },
];


export const employeeSectionRows: Row[] = [
  { Id: 1, EmployeeName: 'Alice Lee', Department: 'Engineering', Title: 'Senior Dev', StartDate: '2020-07-01', Active: true },
  { Id: 2, EmployeeName: 'Bob Singh', Department: 'Finance', Title: 'Analyst', StartDate: '2021-03-15', Active: true },
  { Id: 3, EmployeeName: 'Carla Nair', Department: 'Engineering', Title: 'Dev', StartDate: '2022-11-20', Active: false },
  { Id: 4, EmployeeName: 'David Wang', Department: 'HR', Title: 'HRBP', StartDate: '2019-01-10', Active: true },
  { Id: 5, EmployeeName: 'Elena Kumar', Department: 'Sales', Title: 'AE', StartDate: '2023-05-04', Active: true },
];

