import { Row } from "../components/controls/customcomponent/grid/utils/types";


export const employeeRows: Row[] = [
  {
    Id: 1,
    EmployeeName: 'Aarav Mehta',
    Department: 'Engineering',
    Designation: 'Senior Developer',
    Email: 'aarav.mehta@example.com',
    Phone: '9876543210',
    City: 'Bangalore',
    JoinDate: '2023-05-10',
    Experience: 5,
    Manager: 'Neha Kapoor',
    Active: true,
    Salary: 1200000,
    Remarks: 'High performer, works on critical projects',
  },
  {
    Id: 2,
    EmployeeName: 'Diya Sharma',
    Department: 'Finance',
    Designation: 'Account Executive',
    Email: 'diya.sharma@example.com',
    Phone: '9823412345',
    City: 'Mumbai',
    JoinDate: '2022-11-01',
    Experience: 3,
    Manager: 'Rajesh Nair',
    Active: false,
    Salary: 900000,
    Remarks: 'On sabbatical leave',
  },
  {
    Id: 3,
    EmployeeName: 'Rohit Kumar',
    Department: 'HR',
    Designation: 'HR Manager',
    Email: 'rohit.kumar@example.com',
    Phone: '9998887776',
    City: 'Pune',
    JoinDate: '2024-02-15',
    Experience: 6,
    Manager: 'Meera Sen',
    Active: true,
    Salary: 750000,
    Remarks: 'Leads employee engagement initiatives',
  },
  {
    Id: 4,
    EmployeeName: 'Sara Iyer',
    Department: 'Engineering',
    Designation: 'Tech Lead',
    Email: 'sara.iyer@example.com',
    Phone: '9812345678',
    City: 'Chennai',
    JoinDate: '2021-08-22',
    Experience: 8,
    Manager: 'Neha Kapoor',
    Active: true,
    Salary: 1500000,
    Remarks: 'Excellent leadership and mentoring skills',
  },
  {
    Id: 5,
    EmployeeName: 'Kabir Jain',
    Department: 'Sales',
    Designation: 'Sales Executive',
    Email: 'kabir.jain@example.com',
    Phone: '9867895432',
    City: 'Delhi',
    JoinDate: '2020-01-05',
    Experience: 4,
    Manager: 'Vikas Sharma',
    Active: false,
    Salary: 650000,
    Remarks: 'Recently moved to part-time consultancy',
  },
  {
    Id: 6,
    EmployeeName: 'Priya Menon',
    Department: 'Marketing',
    Designation: 'Digital Marketing Lead',
    Email: 'priya.menon@example.com',
    Phone: '9845098765',
    City: 'Hyderabad',
    JoinDate: '2019-03-12',
    Experience: 7,
    Manager: 'Ravi Patel',
    Active: true,
    Salary: 1100000,
    Remarks: 'Handles social campaigns and analytics',
  },
];


export const employeeSectionRows: Row[] = [
  { Id: 1, EmployeeName: 'Alice Lee', Department: 'Engineering', Title: 'Senior Dev', StartDate: '2020-07-01', Active: true },
  { Id: 2, EmployeeName: 'Bob Singh', Department: 'Finance', Title: 'Analyst', StartDate: '2021-03-15', Active: true },
  { Id: 3, EmployeeName: 'Carla Nair', Department: 'Engineering', Title: 'Dev', StartDate: '2022-11-20', Active: false },
  { Id: 4, EmployeeName: 'David Wang', Department: 'HR', Title: 'HRBP', StartDate: '2019-01-10', Active: true },
  { Id: 5, EmployeeName: 'Elena Kumar', Department: 'Sales', Title: 'AE', StartDate: '2023-05-04', Active: true },
  { Id: 6, EmployeeName: 'Faisal Khan', Department: 'Engineering', Title: 'Tech Lead', StartDate: '2018-09-12', Active: true },
  { Id: 7, EmployeeName: 'Grace Taylor', Department: 'Marketing', Title: 'Coordinator', StartDate: '2022-02-25', Active: true },
  { Id: 8, EmployeeName: 'Himanshu Patel', Department: 'Support', Title: 'Support Eng', StartDate: '2021-11-08', Active: true },
  { Id: 9, EmployeeName: 'Irene Zhao', Department: 'HR', Title: 'Recruiter', StartDate: '2020-05-17', Active: false },
  { Id: 10, EmployeeName: 'Jack Wilson', Department: 'Engineering', Title: 'Architect', StartDate: '2017-03-30', Active: true },
  { Id: 11, EmployeeName: 'Karan Mehta', Department: 'Finance', Title: 'Sr Analyst', StartDate: '2022-01-15', Active: true },
  { Id: 12, EmployeeName: 'Laura Chen', Department: 'Admin', Title: 'Office Manager', StartDate: '2019-08-22', Active: true },
  { Id: 13, EmployeeName: 'Mohit Sharma', Department: 'Engineering', Title: 'Dev', StartDate: '2023-02-10', Active: true },
  { Id: 14, EmployeeName: 'Nina Brown', Department: 'Sales', Title: 'Sales Manager', StartDate: '2020-10-05', Active: true },
  { Id: 15, EmployeeName: 'Omar Ali', Department: 'Support', Title: 'Support Eng', StartDate: '2021-06-18', Active: false },
  { Id: 16, EmployeeName: 'Priya Kapoor', Department: 'HR', Title: 'HR Manager', StartDate: '2018-04-29', Active: true },
  { Id: 17, EmployeeName: 'Qi Zhang', Department: 'Engineering', Title: 'DevOps Eng', StartDate: '2022-07-12', Active: true },
  { Id: 18, EmployeeName: 'Rahul Verma', Department: 'Finance', Title: 'Accountant', StartDate: '2019-12-03', Active: true },
  { Id: 19, EmployeeName: 'Sara Lee', Department: 'Marketing', Title: 'Content Writer', StartDate: '2020-02-11', Active: false },
  { Id: 20, EmployeeName: 'Tom Gray', Department: 'Engineering', Title: 'QA Engineer', StartDate: '2021-09-09', Active: true },
  { Id: 21, EmployeeName: 'Uma Devi', Department: 'Operations', Title: 'Ops Manager', StartDate: '2018-11-19', Active: true },
  { Id: 22, EmployeeName: 'Vikram Singh', Department: 'Engineering', Title: 'Team Lead', StartDate: '2017-12-27', Active: true },
  { Id: 23, EmployeeName: 'William Clark', Department: 'Sales', Title: 'Account Exec', StartDate: '2022-03-21', Active: true },
  { Id: 24, EmployeeName: 'Xiao Li', Department: 'Support', Title: 'Support Lead', StartDate: '2019-07-14', Active: true },
  { Id: 25, EmployeeName: 'Yusuf Pathan', Department: 'Engineering', Title: 'Intern', StartDate: '2023-06-01', Active: true },
  { Id: 26, EmployeeName: 'Zara Khan', Department: 'Marketing', Title: 'SEO Specialist', StartDate: '2021-01-20', Active: true },
  { Id: 27, EmployeeName: 'Ankit Patel', Department: 'Engineering', Title: 'Dev', StartDate: '2020-09-30', Active: true },
  { Id: 28, EmployeeName: 'Bella Morris', Department: 'Finance', Title: 'Finance Manager', StartDate: '2019-02-17', Active: true },
  { Id: 29, EmployeeName: 'Chetan Joshi', Department: 'Admin', Title: 'Admin Assistant', StartDate: '2021-04-10', Active: true },
  { Id: 30, EmployeeName: 'Divya Rao', Department: 'HR', Title: 'HR Executive', StartDate: '2022-08-09', Active: true },
];

